# This is a basic workflow to help you get started with Actions

name: CI

# This workflow is triggered on pushes and PRs to the repository.
# It runs the pipeline with the minimal test dataset to check that it completes without any syntax errors
on: [push, pull_request]

jobs:
  test:
    env:
      NXF_VER: ${{ matrix.nxf_ver }}
      NXF_ANSI_LOG: false
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Nextflow versions: check pipeline minimum and current latest
        nxf_ver: ['20.04.0', '']
    steps:
      - uses: actions/checkout@v2
      - name: Install Nextflow
        run: |
          wget -qO- get.nextflow.io | bash
          sudo mv nextflow /usr/local/bin/
      - name: Pull docker image
        run: |
          docker pull peterk87/nf-illmap:latest
          docker tag peterk87/nf-illmap:latest peterk87/nf-illmap:latest
      - name: Run pipeline with test data
        run: |
          nextflow run ${GITHUB_WORKSPACE} --help
          nextflow run ${GITHUB_WORKSPACE} -profile docker,test
